// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV6IdhYYMwA5x8z17ogp2G1-J_2o7-Qcg',
    appId: '1:933002366079:web:e10dba82bfefeaf598434a',
    messagingSenderId: '933002366079',
    projectId: 'campusskillswap-a9f45',
    authDomain: 'campusskillswap-a9f45.firebaseapp.com',
    storageBucket: 'campusskillswap-a9f45.firebasestorage.app',
    measurementId: 'G-35KNKG1DSM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHzl_ELKR3uiDhWj58hmKx_Mdsthh0w70',
    appId: '1:933002366079:android:3e321ee281faccc398434a',
    messagingSenderId: '933002366079',
    projectId: 'campusskillswap-a9f45',
    storageBucket: 'campusskillswap-a9f45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD33bDeVQoF-z3ZTjgbsPABwGkxf6pr8s0',
    appId: '1:933002366079:ios:135f73ba4260ca5798434a',
    messagingSenderId: '933002366079',
    projectId: 'campusskillswap-a9f45',
    storageBucket: 'campusskillswap-a9f45.firebasestorage.app',
    iosBundleId: 'com.example.campusSkillswap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD33bDeVQoF-z3ZTjgbsPABwGkxf6pr8s0',
    appId: '1:933002366079:ios:135f73ba4260ca5798434a',
    messagingSenderId: '933002366079',
    projectId: 'campusskillswap-a9f45',
    storageBucket: 'campusskillswap-a9f45.firebasestorage.app',
    iosBundleId: 'com.example.campusSkillswap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV6IdhYYMwA5x8z17ogp2G1-J_2o7-Qcg',
    appId: '1:933002366079:web:67c388f78b3adc5c98434a',
    messagingSenderId: '933002366079',
    projectId: 'campusskillswap-a9f45',
    authDomain: 'campusskillswap-a9f45.firebaseapp.com',
    storageBucket: 'campusskillswap-a9f45.firebasestorage.app',
    measurementId: 'G-14QR2S882Y',
  );
}
